### Assignment_WebScraping_4

In [1]:
#IMPORTING LIBRARIES
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
import time
from selenium.webdriver.chrome.options import Options
chrome_options = Options()
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

# Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [58]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the youtube wikepedia URL
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
time.sleep(5)
# Loading table parent tag
table_prnt_tag_elem = driver.find_element_by_xpath('/html/body/div[3]/div[3]/div[5]/div[1]/table[4]')
# Loading tr child tag of table_prnt_tag_elem
child_tags = table_prnt_tag_elem.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[4]/tbody/tr')
video_name = []
rank = []
uploader_name = []
views_list=[]
upload_date_list = []
vid_name_count = 1
# looping through all the child tags
for i in child_tags:
    
    # Extracting video name from child tag
    try:
        video_name.append(i.find_element_by_xpath(f'//*[@id="mw-content-text"]/div[1]/table[4]/tbody/tr[{vid_name_count}]/td[1]/a').text)  
    except NoSuchElementException:
        pass
    rank.append(vid_name_count)
    # Extracting uploader name from child tag
    try:
        uploader_name.append(i.find_element_by_xpath(f'//*[@id="mw-content-text"]/div[1]/table[4]/tbody/tr[{vid_name_count}]/td[2]/a').text)
    except NoSuchElementException:
        try:
            uploader_name.append(i.find_element_by_xpath(f'//*[@id="mw-content-text"]/div[1]/table[4]/tbody/tr[{vid_name_count}]/td[2]').text)
        except NoSuchElementException:
            pass
    # Extracting views from child tag
    try:
        views_list.append(i.find_element_by_xpath(f'//*[@id="mw-content-text"]/div[1]/table[4]/tbody/tr[{vid_name_count}]/td[3]').text)
    except NoSuchElementException:
            pass
    # Extracting upload_date from child tag
    try:
        upload_date_list.append(i.find_element_by_xpath(f'//*[@id="mw-content-text"]/div[1]/table[4]/tbody/tr[{vid_name_count}]/td[4]').text)
    except NoSuchElementException:
            pass 
    # Incresing the count to extract items in next loop
    vid_name_count=vid_name_count+1
driver.close()
youtube_df = pd.DataFrame({})
youtube_df['Rank']=rank
youtube_df['Video Name'] = video_name
youtube_df['Artist']=uploader_name
youtube_df['Upload date']=upload_date_list
youtube_df['Views']=views_list
youtube_df

,Rank,Video Name,Artist,Upload date,Views
0,1,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016","7,037,500,000"
1,2,Despacito,Luis Fonsi,"January 12, 2017","2,993,700,000"
2,3,See You Again,Wiz Khalifa,"April 6, 2015","2,894,000,000"
3,4,Gangnam Style,Psy,"July 15, 2012","803,700,000"
4,5,Baby,Justin Bieber,"February 19, 2010","245,400,000"
5,6,Bad Romance,Lady Gaga,"November 24, 2009","178,400,000"
6,7,Charlie Bit My Finger,HDCYT,"May 22, 2007","128,900,000"
7,8,Evolution of Dance,Judson Laipply,"April 6, 2006","118,900,000"
8,9,Girlfriend,RCA Records,"February 27, 2007","92,600,000"
9,10,Evolution of Dance,Judson Laipply,"April 6, 2006","78,400,000"
10,11,Music Is My Hot Hot Sex,CLARUSBARTEL72,"April 9, 2007","76,600,000"
11,12,Evolution of Dance,Judson Laipply,"April 6, 2006","10,600,000"
12,13,Pokemon Theme Music Video,Smosh,"November 28, 2005","4,300,000"
13,14,Myspace – The Movie,eggtea,"January 31, 2006","2,700,000"
14,15,Phony Photo Booth,mugenized,"December 1, 2005","3,400,000"
15,16,The Chronic of Narnia Rap,youtubedude,"December 18, 2005","2,300,000"
16,17,Ronaldinho: Touch of Gold,Nikesoccer,"October 21, 2005","255,000"
17,18,I/O Brush,larfus,"October 5, 2005","247,000"
18,19,Me at the zoo,jawed,"April 23, 2005",1

# Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [99]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the https://www.bcci.tv/ URL
driver.get('https://www.bcci.tv/')
time.sleep(5)
# Getting fixture href link
fix_link = driver.find_element_by_xpath('/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a').get_attribute('href')
driver.get(fix_link)
time.sleep(5)
# Getting parent tag
matches_body = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div')
# Getting all child tags related to parent tags
get_matches_tag=matches_body.find_elements_by_xpath('//*[@id="fixtures"]/div[3]/div/div')
Match_title = []
match_loc = []
match_series = []
match_date = []
match_time = []
matchnum=1
# Looping through all child tags
for i in get_matches_tag:
    # Getting match title
    Match_title.append(i.find_element_by_xpath(f'/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div[{matchnum}]/div/div[4]/div/span[1]').text.replace(" -",""))
    # Extracting match location
    match_loc.append(i.find_element_by_xpath(f'/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div[{matchnum}]/div/div[4]/div/span[2]').text)
    # Extracting series names
    match_series.append(i.find_element_by_xpath(f'//*[@id="fixtures"]/div[3]/div/div[{matchnum}]/div/div[1]/h5[2]/span').text)
    # Extracting match date
    match_date.append(i.find_element_by_xpath(f'//*[@id="fixtures"]/div[3]/div/div[{matchnum}]/div/div[1]/div/div[1]/h5').text)
    # Extracting match time
    match_time.append(i.find_element_by_xpath(f'//*[@id="fixtures"]/div[3]/div/div[{matchnum}]/div/div[1]/div/div[2]/h5').text)
    matchnum+=1
driver.close()
# Ceating a DataFrame
bcci_df = pd.DataFrame({})
bcci_df['Match title']=Match_title
bcci_df['Series'] = match_series
bcci_df['Place']=match_loc
bcci_df['Date']=match_date
bcci_df['Time']=match_time
bcci_df

,Match title,Series,Place,Date,Time
0,1st T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Arun Jaitley Stadium,",9 JUN 2022,7:00 PM IST
1,2nd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Barabati Stadium,",12 JUN 2022,7:00 PM IST
2,3rd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",14 JUN 2022,7:00 PM IST
3,4th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Saurashtra Cricket Association Stadium,",17 JUN 2022,7:00 PM IST
4,5th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"M Chinnaswamy Stadium,",19 JUN 2022,7:00 PM IST

# Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [115]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the https://www.guru99.com/ URL
driver.get('https://www.guru99.com/')
time.sleep(5)
sel_tag = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[2]/span[8]/a').get_attribute('href')
driver.get(sel_tag)
time.sleep(3)
driver.get(driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href'))
time.sleep(3)
get_exec_table_tag = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table/tbody')
get_tr_tags=get_exec_table_tag.find_elements_by_xpath('//*[@id="post-1953"]/div/div/table/tbody/tr')
exec_type=[]
exec_desc = []
get_exec_info_cnt = 2
for i in get_tr_tags[1::]:
    exec_type.append(i.find_element_by_xpath(f'//*[@id="post-1953"]/div/div/table/tbody/tr[{get_exec_info_cnt}]/td[1]').text)
    exec_desc.append(i.find_element_by_xpath(f'//*[@id="post-1953"]/div/div/table/tbody/tr[{get_exec_info_cnt}]/td[2]').text)
    get_exec_info_cnt+=1
driver.close()
# Ceating a DataFrame
guru_99_df = pd.DataFrame({})
guru_99_df['Exception Type']=exec_type
guru_99_df['Exception Description'] = exec_desc
guru_99_df

,Exception Type,Exception Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [132]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the http://statisticstimes.com/ URL
driver.get('http://statisticstimes.com/')
time.sleep(5)
# getting economy tag
driver.get(driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]').get_attribute('href'))
time.sleep(5)
# Selectng indian gdp link from economy tag
driver.get(WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, '/html/body/div[2]/div[2]/div[2]/ul/li[1]/a'))).get_attribute('href'))
# getting tbody and tr tag
tbody_tag = driver.find_element_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody')
tr_tags = tbody_tag.find_elements_by_xpath('//*[@id="table_id"]/tbody/tr')

ranks = []
states = []
gsdp_17_18 = []
gsdp_18_19 = []
gsdp_19_20 = []
share_2017 = []
share_18_19=[]
gdp = []
tr_num = 1
# Looping through different tr tags
for i in tr_tags:
    # Extracting ranks,states, gsdp_17_18, gsdp_18_19, gsdp_19_20, share_2017, share_18_19, gdp
    # As share 2017 and gsdp 17-18 is not present adding as '-'
    ranks.append(i.find_element_by_xpath(f'//*[@id="table_id"]/tbody/tr[{tr_num}]/td[1]').text)
    states.append(i.find_element_by_xpath(f'//*[@id="table_id"]/tbody/tr[{tr_num}]/td[2]').text)
    gsdp_17_18.append('-')
    gsdp_18_19.append(i.find_element_by_xpath(f'//*[@id="table_id"]/tbody/tr[{tr_num}]/td[4]').text)
    gsdp_19_20.append(i.find_element_by_xpath(f'//*[@id="table_id"]/tbody/tr[{tr_num}]/td[3]').text)
    share_2017.append('-')
    share_18_19.append(i.find_element_by_xpath(f'//*[@id="table_id"]/tbody/tr[{tr_num}]/td[5]').text)
    gdp.append(i.find_element_by_xpath(f'//*[@id="table_id"]/tbody/tr[{tr_num}]/td[6]').text)
    tr_num+=1
driver.close()
statistic_times_df = pd.DataFrame({})
statistic_times_df['Rank']=ranks
statistic_times_df['States'] = states
statistic_times_df['GSDP 17-18']=gsdp_17_18
statistic_times_df['GSDP 18-19']=gsdp_18_19
statistic_times_df['GSDP 19-20']=gsdp_19_20
statistic_times_df['Share 2017']=share_2017
statistic_times_df['Share 18-19']=share_18_19
statistic_times_df['GDP']=gdp
statistic_times_df

,Rank,States,GSDP 17-18,GSDP 18-19,GSDP 19-20,Share 2017,Share 18-19,GDP
0,1,Maharashtra,-,"2,632,792",-,-,13.94%,399.921
1,2,Tamil Nadu,-,"1,630,208","1,845,853",-,8.63%,247.629
2,3,Uttar Pradesh,-,"1,584,764","1,687,818",-,8.39%,240.726
3,4,Gujarat,-,"1,502,899",-,-,7.96%,228.290
4,5,Karnataka,-,"1,493,127","1,631,977",-,7.91%,226.806
5,6,West Bengal,-,"1,089,898","1,253,832",-,5.77%,165.556
6,7,Rajasthan,-,"942,586","1,020,989",-,4.99%,143.179
7,8,Andhra Pradesh,-,"862,957","972,782",-,4.57%,131.083
8,9,Telangana,-,"861,031","969,604",-,4.56%,130.791
9,10,Madhya Pradesh,-,"809,592","906,672",-,4.29%,122.977
10,11,Kerala,-,"781,653",-,-,4.14%,118.733
11,12,Delhi,-,"774,870","856,112",-,4.10%,117.703
12,13,Haryana,-,"734,163","831,610",-,3.89%,111.519
13,14,Bihar,-,"530,363","611,804",-,2.81%,80.562
14,15,Punjab,-,"526,376","574,760",-,2.79%,79.957
15,16,Odisha,-,"487,805","521,275",-,2.58%,74.098
16,17,Assam,-,"315,881",-,-,1.67%,47.982
17,18,Chhattisgarh,-,"304,063","329,180",-,1.61%,46.187
18,19,Jharkhand,-,"297,204","328,598",-,1.57%,45.145
19,20,Uttarakhand,-,"245,895",-,-,1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",-,-,0.83%,23.690
21,22,Himachal Pradesh,-,"153,845","165,472",-,0.81%,23.369
22,23,Goa,-,"73,170","80,449",-,0.39%,11.115
23,24,Tripura,-,"49,845","55,984",-,0.26%,7.571
24,25,Chandigarh,-,"42,114",-,-,0.22%,6.397
25,26,Puducherry,-,"34,433","38,253",-,0.18%,5.230
26,27,Meghalaya,-,"33,481","36,572",-,0.18%,5.086
27,28,Sikkim,-,"28,723","32,496",-,0.15%,4.363
28,29,Manipur,-,"27,870","31,790",-,0.15%,4.233
29,30,Nagaland,-,"27,283",-,-,0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",-,-,0.13%,3.737
31,32,Mizoram,-,"22,287","26,503",-,0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-,-,-

# Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [3]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the https://github.com/ URL
driver.get('https://github.com/')
time.sleep(5)
driver.get(driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a').get_attribute('href'))

In [24]:
repo_tags = driver.find_elements_by_xpath('/html/body/div[4]/main/div[3]/div/div[2]/article')
repo_names = []
repo_desc = []
repo_contr = []
repo_lang = []
repo_rows = 1
for i in repo_tags:
    repo_names.append(i.find_element_by_xpath(f'//*[@id="js-pjax-container"]/div[3]/div/div[2]/article[{repo_rows}]/h1/a').text)
    repo_desc.append(i.find_element_by_xpath(f'//*[@id="js-pjax-container"]/div[3]/div/div[2]/article[{repo_rows}]/p').text)
    if i.find_elements_by_xpath(f'//*[@id="js-pjax-container"]/div[3]/div/div[2]/article[{repo_rows}]/div[2]/span[2]/a'):
        repo_contr.append(len(i.find_elements_by_xpath(f'//*[@id="js-pjax-container"]/div[3]/div/div[2]/article[{repo_rows}]/div[2]/span[2]/a')))
    else:
        repo_contr.append(len(i.find_elements_by_xpath(f'//*[@id="js-pjax-container"]/div[3]/div/div[2]/article[{repo_rows}]/div[2]/span[1]/a')))
    try:
        repo_lang.append(i.find_element_by_xpath(f'//*[@id="js-pjax-container"]/div[3]/div/div[2]/article[{repo_rows}]/div[2]/span[1]/span[2]').text)
    except NoSuchElementException:
        repo_lang.append('-')
    repo_rows+=1
driver.close()
github_df = pd.DataFrame({})
github_df['Repository Title']=repo_names
github_df['Repository Description'] = repo_desc
github_df['Contributors Count']=repo_contr
github_df['Language']=repo_lang
github_df

,Repository Title,Repository Description,Contributors Count,Language
0,rocboss / paopao-ce,"🔥A artistic ""twitter like"" community built on ...",3,Go
1,zijie0 / HumanSystemOptimization,健康学习到150岁 - 人体系统调优不完全指南,2,-
2,Grasscutters / Grasscutter,A server software reimplementation for a certa...,5,Java
3,neondatabase / neon,The serverless open source alternative to AWS ...,5,Rust
4,trekhleb / javascript-algorithms,📝 Algorithms and data structures implemented i...,5,JavaScript
5,requarks / wiki,Wiki.js | A modern and powerful wiki app built...,5,Vue
6,smartcontractkit / full-blockchain-solidity-co...,"Learn Blockchain, Solidity, and Full Stack Web...",2,-
7,hasinhayder / hydra,Hydra is a zero-config API boilerplate with La...,5,PHP
8,Asabeneh / 30-Days-Of-React,30 Days of React challenge is a step by step g...,5,JavaScript
9,livebud / bud,The Full-Stack Web Framework for Go,5,JavaScript
10,TomSchimansky / CustomTkinter,A modern and customizable python UI-library ba...,5,Python
11,ripienaar / free-for-dev,"A list of SaaS, PaaS and IaaS offerings that h...",5,HTML
12,helix-editor / helix,A post-modern modal text editor.,5,Rust
13,Cveinnt / LiveTerm,💻 Build terminal styled websites in minutes!,3,TypeScript
14,BishopFox / sliver,Adversary Emulation Framework,5,Go
15,cotes2020 / jekyll-theme-chirpy,"A minimal, responsive, and powerful Jekyll the...",5,HTML
16,topjohnwu / Magisk,The Magic Mask for Android,5,C++
17,eludadev / css-buttons,"100 Modern CSS Buttons, Free And Royalty Free.",1,CSS
18,neovim / neovim,Vim-fork focused on extensibility and usability,5,Vim script
19,skyline-emu / skyline,Run Nintendo Switch homebrew & games on your A...,5,C++
20,ageitgey / face_recognition,The world's simplest facial recognition api fo...,5,Python
21,qmk / qmk_firmware,Open-source keyboard firmware for Atmel AVR an...,5,C
22,zju3dv / OnePose,"Code for ""OnePose: One-Shot Object Pose Estima...",1,-
23,yangshun / tech-interview-handbook,💯 Curated interview preparation materials for ...,5,JavaScript
24,coolsnowwolf / lede,Lean's OpenWrt source,5,C

# Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [61]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the www.billboard.com/  URL
driver.get('https://www.billboard.com/')
time.sleep(5)
driver.get(driver.find_element_by_xpath('/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a').get_attribute('href'))
time.sleep(2)
driver.get(driver.find_element_by_xpath('/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a').get_attribute('href'))
time.sleep(5)
driver.get(driver.find_element_by_xpath('/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a').get_attribute('href'))

In [65]:

tble_parnt_tag=driver.find_element_by_xpath('/html/body/div[4]/main/div[2]/div[3]/div/div/div/div[2]')
child_tags = tble_parnt_tag.find_elements_by_class_name('o-chart-results-list-row-container')

In [81]:
song_names = []
song_artist = []
last_week_ranks = []
peak_ranks = []
weeks_on_board = []
row = 2
for i in child_tags:
    song_names.append(i.find_element_by_id('title-of-a-story').text)
    #last_week_ranks.append(i.find_element_by_xpath(f'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div[{row}]/ul/li[4]/ul/li[4]/span'))
    
    row+=1
    
for j in range(1,111):
    try:
        song_artist.append(i.find_element_by_xpath(f'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div[{j}]/ul/li[4]/ul/li[1]/span').text)
    except NoSuchElementException:
        pass
    try:
        last_week_ranks.append(i.find_element_by_xpath(f'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div[{j}]/ul/li[4]/ul/li[4]/span').text)
    except NoSuchElementException:
        pass
    try:
        peak_ranks.append(i.find_element_by_xpath(f'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div[{j}]/ul/li[4]/ul/li[5]/span').text)
    except NoSuchElementException:
        pass
    try:
        weeks_on_board.append(i.find_element_by_xpath(f'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div[{j}]/ul/li[4]/ul/li[6]/span').text)
    except NoSuchElementException:
        pass
driver.close()
billboard_df = pd.DataFrame({})
billboard_df['Song Name']=song_names
billboard_df['Artist'] = song_artist
billboard_df['Last Week Ranks']=last_week_ranks
billboard_df['Peak Rank']=peak_ranks
billboard_df['Weeks On Board']=weeks_on_board
billboard_df

,Song Name,Artist,Last Week Ranks,Peak Rank,Weeks On Board
0,First Class,Jack Harlow,1,1,6
1,As It Was,Harry Styles,2,1,7
2,N95,Kendrick Lamar,-,3,1
3,Wait For U,Future Featuring Drake & Tems,3,1,3
4,Die Hard,"Kendrick Lamar, Blxst & Amanda Reifer",-,5,1
...,...,...,...,...,...
95,The Motto,Tiesto & Ava Max,95,42,16
96,Me Fui de Vacaciones,Bad Bunny,59,59,2
97,Hold My Hand,Lady Gaga,82,82,2
98,Ensename A Bailar,Bad Bunny,60,60,2
99,Flowers,Lauren Spencer-Smith,93,55,5

# Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [85]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the www.theguardian.com/  URL
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
time.sleep(5)
parent_tbody_tag = driver.find_element_by_xpath('/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody')
child_tr_tags = parent_tbody_tag.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr')

In [91]:
cnt = 0
book_names = []
author_names = []
volumes_sold = []
publishers = []
genres = []
for i in child_tr_tags:
    book_names.append(i.find_element_by_id(f'table-cell-10943-{cnt}-1').text)
    author_names.append(i.find_element_by_id(f'table-cell-10943-{cnt}-2').text)
    volumes_sold.append(i.find_element_by_id(f'table-cell-10943-{cnt}-3').text)
    publishers.append(i.find_element_by_id(f'table-cell-10943-{cnt}-4').text)
    genres.append(i.find_element_by_id(f'table-cell-10943-{cnt}-5').text)
    cnt+=1
driver.close()
guardian_df = pd.DataFrame({})
guardian_df['Book Name']=book_names
guardian_df['Author Name'] = author_names
guardian_df['Volumes Sold']=volumes_sold
guardian_df['Publisher']=publishers
guardian_df['Genre']=genres
guardian_df

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [92]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the https://www.imdb.com/list/ls095964455/  URL
driver.get('https://www.imdb.com/list/ls095964455/')
time.sleep(5)
parent_tag = driver.find_elements_by_xpath('/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div')

In [114]:
tv_shows=[]
years=[]
genres = []
run_times = []
ratings = []
votes = []
cnt=1
for i in parent_tag:
    tv_shows.append(i.find_element_by_xpath(f'//*[@id="main"]/div/div[3]/div[3]/div[{cnt}]/div[2]/h3/a').text)
    year = i.find_element_by_xpath(f'//*[@id="main"]/div/div[3]/div[3]/div[{cnt}]/div[2]/h3/span[2]').text
    year = year.replace('(','')
    year = year.replace(')','')
    years.append(year)
    genres.append(i.find_element_by_xpath(f'//*[@id="main"]/div/div[3]/div[3]/div[{cnt}]/div[2]/p[1]/span[5]').text)
    run_times.append(i.find_element_by_xpath(f'//*[@id="main"]/div/div[3]/div[3]/div[{cnt}]/div[2]/p[1]/span[3]').text)
    ratings.append(i.find_element_by_xpath(f'//*[@id="main"]/div/div[3]/div[3]/div[{cnt}]/div[2]/div[1]/div[1]/span[2]').text)
    votes.append(i.find_element_by_xpath(f'//*[@id="main"]/div/div[3]/div[3]/div[{cnt}]/div[2]/p[4]/span[2]').text)    
    cnt+=1
driver.close()
imdb_df = pd.DataFrame({})
imdb_df['TV Show']=tv_shows
imdb_df['Year Span'] = years
imdb_df['Genre']=genres
imdb_df['Run Time']=run_times
imdb_df['Rating']=ratings
imdb_df['Votes']=votes
imdb_df

,TV Show,Year Span,Genre,Run Time,Rating,Votes
0,Game of Thrones,2011–2019,"Action, Adventure, Drama",57 min,9.2,"1,990,259"
1,Stranger Things,2016–,"Drama, Fantasy, Horror",51 min,8.7,"1,007,688"
2,The Walking Dead,2010–2022,"Drama, Horror, Thriller",44 min,8.2,"947,735"
3,13 Reasons Why,2017–2020,"Drama, Mystery, Thriller",60 min,7.5,"283,147"
4,The 100,2014–2020,"Drama, Mystery, Sci-Fi",43 min,7.6,"242,955"
...,...,...,...,...,...,...
95,Reign,2013–2017,"Drama, Fantasy",42 min,7.4,"48,775"
96,A Series of Unfortunate Events,2017–2019,"Adventure, Comedy, Drama",50 min,7.8,"59,428"
97,Criminal Minds,2005–2020,"Crime, Drama, Mystery",42 min,8.1,"189,884"
98,Scream: The TV Series,2015–2019,"Comedy, Crime, Drama",45 min,7.1,"40,206"
99,The Haunting of Hill House,2018,"Drama, Horror, Mystery",572 min,8.6,"227,963"

# Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [115]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the https://archive.ics.uci.edu/  URL
driver.get('https://archive.ics.uci.edu/')
time.sleep(5)
driver.get(driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a').get_attribute('href'))

In [116]:
parent_tag = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody')
child_tags = parent_tag.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr')

In [129]:
datasets = []
datatypes = []
datatasks = []
attributetypes = []
instances = []
attributes = []
years = []
cnt=2
for i in child_tags:
    try:
        datasets.append(i.find_element_by_xpath(f'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{cnt}]/td[1]/table/tbody/tr/td[2]/p/b/a').text)
    except NoSuchElementException:
        pass
    try:
        datatypes.append(i.find_element_by_xpath(f'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{cnt}]/td[2]/p').text)
    except NoSuchElementException:
        pass
    try:
        datatasks.append(i.find_element_by_xpath(f'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{cnt}]/td[3]/p').text)
    except NoSuchElementException:
        pass
    try:
        attributetypes.append(i.find_element_by_xpath(f'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{cnt}]/td[4]/p').text)
    except NoSuchElementException:
        pass
    try:
        instances.append(i.find_element_by_xpath(f'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{cnt}]/td[5]/p').text)
    except NoSuchElementException:
        pass
    try:
        attributes.append(i.find_element_by_xpath(f'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{cnt}]/td[6]/p').text)
    except NoSuchElementException:
        pass
    try:
        years.append(i.find_element_by_xpath(f'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{cnt}]/td[7]/p').text)
    except NoSuchElementException:
        pass
    cnt+=1
driver.close()
uci_df = pd.DataFrame({})
uci_df['Dataset']=datasets
uci_df['Data Type'] = datatypes
uci_df['Task']=datatasks
uci_df['Attribute Type']=attributetypes
uci_df['No of Instances']=instances
uci_df['No of Attributes']=attributes
uci_df['Year']=years
uci_df

,Dataset,Data Type,Task,Attribute Type,No of Instances,No of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

# Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

As i dont have recruiters option in the naukri home page calling it directly as per the ticket raised(https://www.flipnwork.com/index.php/tickets/view/9646)

In [37]:
# Intializing the chrome driver
driver = webdriver.Chrome('/Users/akhilmatta/chromedriver')
#Loading the https://www.naukri.com/hr-recruiters-consultants  URL
driver.get('https://www.naukri.com/hr-recruiters-consultants')
time.sleep(5)

In [38]:
parent_tag = driver.find_element_by_xpath('/html/body/div[3]/div[1]/div[1]/div[2]/div/div/div[1]/div[1]/div')

In [39]:
child_tags = parent_tag.find_elements_by_xpath('//*[@id="tuples1"]/div/div')

In [40]:
recruiter_names = []
recruiter_designation=[]
recruiter_company = []
skills = []
location = []
cnt_num = 1
for i in child_tags:
    recruiter_names.append(i.find_element_by_xpath(f'//*[@id="tuples1"]/div/div[{cnt_num}]/div[1]/div[1]/p/a[1]/span').text)
    recruiter_designation.append(i.find_element_by_xpath(f'//*[@id="tuples1"]/div/div[{cnt_num}]/div[1]/div[1]/p/span[1]').text)
    recruiter_company.append(i.find_element_by_xpath(f'//*[@id="tuples1"]/div/div[{cnt_num}]/div[1]/div[1]/p/a[2]/small').text)
    skills.append(i.find_element_by_xpath(f'//*[@id="tuples1"]/div/div[{cnt_num}]/div[1]/div[2]').text)
    location.append(i.find_element_by_xpath(f'//*[@id="tuples1"]/div/div[{cnt_num}]/div[1]/div[1]/p/span[2]/small').text)
    cnt_num+=1
driver.close()
naukri_df = pd.DataFrame({})
naukri_df['Recruiter Name']=recruiter_names
naukri_df['Recruiter Designation'] = recruiter_designation
naukri_df['Recruiter Company']=recruiter_company
naukri_df['Hiring for skills']=skills
naukri_df['Location']=location
naukri_df

,Recruiter Name,Recruiter Designation,Recruiter Company,Hiring for skills,Location
0,Santhosh Kumar,Associate Manager Human Resources,Maveric Systems,"It Recruitment, Campus Recruitment, Campus Hir...",Chennai
1,Gauri Bhosle,Human Resources,TCRC,"Operation Executive, Jr. Chemist/ Chemist, Aud...",Mumbai
2,CodeFlies,Human Resources,CodeFlies,"Email Marketing, Communication, Online Lead Ge...",Noida
3,Surendra R,Company Recruiter,DSR Design & Engineering Solutions,"Design Engineering, AutoCAD, Solid Works",Hyderabad / Secunderabad
4,Sanghvi,Company Recruiter,Primacy Systems Pvt Ltd,"Marketing, Sales, Plastic, Aluminium, Metal, S...",Ahmedabad
5,Neha Pandey,Company Recruiter,Ingenious E-Brain Solutions Private Limited,"B.tech, Operations, Business Development, Busi...",Gurgaon
6,Vinita Raut,Company Recruiter,Xpansion HR Solutions Private Limited,"Bde, Accounting, Education Counseling, Sales, ...",Pune
7,Anandi Bandekar,Deputy Manager Recruitment,GeBBS Healthcare Solutions,"CTO, VP, Sr.Manager",Mumbai